Data Validation

By: Josh Navarro

Goal: Learn data validation in jupyter notebook, using python pandas

Data: Synthesized by ChatGPT

In [2]:
# Import that I will be using
import pandas as pd
import numpy as np

In [3]:
# Create the synthetic data
df = pd.DataFrame({
    "student_id": [101, 102, 103, 104, 104, 106, 107, 108],
    "name": ["Alex", "Maria", "John", "Sarah", "Sarah", "", "David", "Emma"],
    "age": [20, 22, -5, 19, 19, 130, 21, np.nan],
    "grade": ["A", "B", "C", "A", "A", "Z", "B", "C"],
    "email": [
        "alex@email.com",
        "maria@email.com",
        "johnemail.com",
        "sarah@email.com",
        "sarah@email.com",
        "no_email",
        "david@email.com",
        None
    ],
    "enrollment_date": [
        "2024-01-10",
        "2024-02-15",
        "not a date",
        "2024-03-01",
        "2024-03-01",
        "2025-01-20",
        "2024-04-12",
        ""
    ],
    "score": [88, 92, 75, 95, 95, 110, -10, np.nan]
})

df

   student_id   name    age grade            email enrollment_date  score
0         101   Alex   20.0     A   alex@email.com      2024-01-10   88.0
1         102  Maria   22.0     B  maria@email.com      2024-02-15   92.0
2         103   John   -5.0     C    johnemail.com      not a date   75.0
3         104  Sarah   19.0     A  sarah@email.com      2024-03-01   95.0
4         104  Sarah   19.0     A  sarah@email.com      2024-03-01   95.0
5         106         130.0     Z         no_email      2025-01-20  110.0
6         107  David   21.0     B  david@email.com      2024-04-12  -10.0
7         108   Emma    NaN     C             None                    NaN

Data Validation

In [5]:
# Create a copy of the dataframe
valid_df = df.copy()
# Check the dataframe
valid_df.head()

   student_id   name   age grade            email enrollment_date  score
0         101   Alex  20.0     A   alex@email.com      2024-01-10   88.0
1         102  Maria  22.0     B  maria@email.com      2024-02-15   92.0
2         103   John  -5.0     C    johnemail.com      not a date   75.0
3         104  Sarah  19.0     A  sarah@email.com      2024-03-01   95.0
4         104  Sarah  19.0     A  sarah@email.com      2024-03-01   95.0

1 Check for missing values

Checking for missing values in a dataframe is done in a couple of ways, but mainly using the isna() function.

In [9]:
# Find the columns that have missing data
missing_data = valid_df.isna()

# Count the missing values in each of the colunmns
count_of_miss = valid_df.isna().sum()

# Also find the rows the column 'age' is going to be missing
missing_age = valid_df[valid_df['age'].isna()]

(missing_data, count_of_miss, missing_age)

(   student_id   name    age  grade  email  enrollment_date  score
 0       False  False  False  False  False            False  False
 1       False  False  False  False  False            False  False
 2       False  False  False  False  False            False  False
 3       False  False  False  False  False            False  False
 4       False  False  False  False  False            False  False
 5       False  False  False  False  False            False  False
 6       False  False  False  False  False            False  False
 7       False  False   True  False   True            False   True,
 student_id         0
 name               0
 age                1
 grade              0
 email              1
 enrollment_date    0
 score              1
 dtype: int64,
    student_id  name  age grade email enrollment_date  score
 7         108  Emma  NaN     C  None                    NaN)

2 Check for empty strings

For empty strings in order you can use the basic query within the data frame, but after you can use .replace to change it to np.nan

In [ ]:
# Find the missing data in name column and the enrollment date column
(
valid_df[valid_df['name'] == ""],
valid_df[valid_df['enrollment_date'] == ""]
)

(   student_id name    age grade     email enrollment_date  score
 5         106       130.0     Z  no_email      2025-01-20  110.0,
    student_id  name  age grade email enrollment_date  score
 7         108  Emma  NaN     C  None                    NaN)

In [13]:
# Replace both the empty strings in both the name, 
# and enrollment date to NA

valid_df['name'] = valid_df['name'].replace("", np.nan)
valid_df['enrollment_date'] = valid_df['enrollment_date'].replace("", np.nan)

# Check the dataframe
valid_df

   student_id   name    age grade            email enrollment_date  score
0         101   Alex   20.0     A   alex@email.com      2024-01-10   88.0
1         102  Maria   22.0     B  maria@email.com      2024-02-15   92.0
2         103   John   -5.0     C    johnemail.com      not a date   75.0
3         104  Sarah   19.0     A  sarah@email.com      2024-03-01   95.0
4         104  Sarah   19.0     A  sarah@email.com      2024-03-01   95.0
5         106    NaN  130.0     Z         no_email      2025-01-20  110.0
6         107  David   21.0     B  david@email.com      2024-04-12  -10.0
7         108   Emma    NaN     C             None             NaN    NaN

3 Check duplicate rows

4 Validate the numeric ranges

5 Validate allowed categories

6 Validate email format

7 Validate date format

8 Check Data Types

9 Check unique values

10 Create validation flags

11 Find rows that failed any validation rule

12 Create a simple validation summary