Data Validation

By: Josh Navarro

Goal: Learn data validation in jupyter notebook, using python pandas

Data: Synthesized by ChatGPT

In [52]:
# Import that I will be using
import pandas as pd
import numpy as np

In [53]:
# Create the synthetic data
df = pd.DataFrame({
    "student_id": [101, 102, 103, 104, 104, 106, 107, 108],
    "name": ["Alex", "Maria", "John", "Sarah", "Sarah", "", "David", "Emma"],
    "age": [20, 22, -5, 19, 19, 130, 21, np.nan],
    "grade": ["A", "B", "C", "A", "A", "Z", "B", "C"],
    "email": [
        "alex@email.com",
        "maria@email.com",
        "johnemail.com",
        "sarah@email.com",
        "sarah@email.com",
        "no_email",
        "david@email.com",
        None
    ],
    "enrollment_date": [
        "2024-01-10",
        "2024-02-15",
        "not a date",
        "2024-03-01",
        "2024-03-01",
        "2025-01-20",
        "2024-04-12",
        ""
    ],
    "score": [88, 92, 75, 95, 95, 110, -10, np.nan]
})

df

   student_id   name    age grade            email enrollment_date  score
0         101   Alex   20.0     A   alex@email.com      2024-01-10   88.0
1         102  Maria   22.0     B  maria@email.com      2024-02-15   92.0
2         103   John   -5.0     C    johnemail.com      not a date   75.0
3         104  Sarah   19.0     A  sarah@email.com      2024-03-01   95.0
4         104  Sarah   19.0     A  sarah@email.com      2024-03-01   95.0
5         106         130.0     Z         no_email      2025-01-20  110.0
6         107  David   21.0     B  david@email.com      2024-04-12  -10.0
7         108   Emma    NaN     C             None                    NaN

Data Validation

In [54]:
# Create a copy of the dataframe
valid_df = df.copy()
# Check the dataframe
valid_df.head()

   student_id   name   age grade            email enrollment_date  score
0         101   Alex  20.0     A   alex@email.com      2024-01-10   88.0
1         102  Maria  22.0     B  maria@email.com      2024-02-15   92.0
2         103   John  -5.0     C    johnemail.com      not a date   75.0
3         104  Sarah  19.0     A  sarah@email.com      2024-03-01   95.0
4         104  Sarah  19.0     A  sarah@email.com      2024-03-01   95.0

1 Check for missing values

Checking for missing values in a dataframe is done in a couple of ways, but mainly using the isna() function.

In [55]:
# Find the columns that have missing data
missing_data = valid_df.isna()

# Count the missing values in each of the colunmns
count_of_miss = valid_df.isna().sum()

# Also find the rows the column 'age' is going to be missing
missing_age = valid_df[valid_df['age'].isna()]

(missing_data, count_of_miss, missing_age)

(   student_id   name    age  grade  email  enrollment_date  score
 0       False  False  False  False  False            False  False
 1       False  False  False  False  False            False  False
 2       False  False  False  False  False            False  False
 3       False  False  False  False  False            False  False
 4       False  False  False  False  False            False  False
 5       False  False  False  False  False            False  False
 6       False  False  False  False  False            False  False
 7       False  False   True  False   True            False   True,
 student_id         0
 name               0
 age                1
 grade              0
 email              1
 enrollment_date    0
 score              1
 dtype: int64,
    student_id  name  age grade email enrollment_date  score
 7         108  Emma  NaN     C  None                    NaN)

2 Check for empty strings

For empty strings in order you can use the basic query within the data frame, but after you can use .replace to change it to np.nan

In [56]:
# Find the missing data in name column and the enrollment date column
(
valid_df[valid_df['name'] == ""],
valid_df[valid_df['enrollment_date'] == ""]
)

(   student_id name    age grade     email enrollment_date  score
 5         106       130.0     Z  no_email      2025-01-20  110.0,
    student_id  name  age grade email enrollment_date  score
 7         108  Emma  NaN     C  None                    NaN)

In [57]:
# Replace both the empty strings in both the name, 
# and enrollment date to NA

valid_df['name'] = valid_df['name'].replace("", np.nan)
valid_df['enrollment_date'] = valid_df['enrollment_date'].replace("", np.nan)

# Check the dataframe
valid_df

   student_id   name    age grade            email enrollment_date  score
0         101   Alex   20.0     A   alex@email.com      2024-01-10   88.0
1         102  Maria   22.0     B  maria@email.com      2024-02-15   92.0
2         103   John   -5.0     C    johnemail.com      not a date   75.0
3         104  Sarah   19.0     A  sarah@email.com      2024-03-01   95.0
4         104  Sarah   19.0     A  sarah@email.com      2024-03-01   95.0
5         106    NaN  130.0     Z         no_email      2025-01-20  110.0
6         107  David   21.0     B  david@email.com      2024-04-12  -10.0
7         108   Emma    NaN     C             None             NaN    NaN

3 Check duplicate rows

Checking for duplicate rows you need to use the function of .duplicated(), with special conditions depending on what you wanna look for

In [58]:
# Find the exact rows that are duplicated exactly
list_dupi = valid_df.duplicated()

# Check the actual rows that are duplcated
rows_dupi = valid_df[valid_df.duplicated()]

# Check the duplicates based upon the one column
col_dupi = valid_df[valid_df.duplicated(subset = "student_id", keep = False)]

# Check the variables
(
    list_dupi,
    rows_dupi,
    col_dupi
)

(0    False
 1    False
 2    False
 3    False
 4     True
 5    False
 6    False
 7    False
 dtype: bool,
    student_id   name   age grade            email enrollment_date  score
 4         104  Sarah  19.0     A  sarah@email.com      2024-03-01   95.0,
    student_id   name   age grade            email enrollment_date  score
 3         104  Sarah  19.0     A  sarah@email.com      2024-03-01   95.0
 4         104  Sarah  19.0     A  sarah@email.com      2024-03-01   95.0)

4 Validate the numeric ranges

Validating the numeric ranges, meaning to check whether the ranges are reasonable in the context of the dataframe. This is done by using conditions or boolean masking.

In [59]:
# Check the range of the ages, to see if there is an age value below 0 or above 85
correct_age = valid_df[(valid_df['age'] < 0) | (valid_df['age'] >= 85)]

# Check the range of scores, to see if there is an score that is below 0 or above 100
correct_score = valid_df[(valid_df['score'] < 0) | (valid_df['score'] >= 100)]

# Check the saved variables
correct_age, correct_score

(   student_id  name    age grade          email enrollment_date  score
 2         103  John   -5.0     C  johnemail.com      not a date   75.0
 5         106   NaN  130.0     Z       no_email      2025-01-20  110.0,
    student_id   name    age grade            email enrollment_date  score
 5         106    NaN  130.0     Z         no_email      2025-01-20  110.0
 6         107  David   21.0     B  david@email.com      2024-04-12  -10.0)

5 Validate allowed categories

Checking whether the values that are in the column make sense in the context of the column. You are able to do this by creating a list, and then using .isin() function.

In [60]:
# Check for valid grades in the grade column
valid_grade = ['A', 'B', 'C', 'D', 'F']

# Check if the values in the grade column are in the list
valid_df[~valid_df['grade'].isin(valid_grade)]

# Note: Using ~ is the same as not(!)

   student_id name    age grade     email enrollment_date  score
5         106  NaN  130.0     Z  no_email      2025-01-20  110.0

6 Validate email format

Checking whether the email format is the same you are able to use the string function .str.contains()

In [61]:
# Find the values that dont have the @ symbol within the email column
valid_df[~valid_df['email'].str.contains("@", na=False)]

   student_id  name    age grade          email enrollment_date  score
2         103  John   -5.0     C  johnemail.com      not a date   75.0
5         106   NaN  130.0     Z       no_email      2025-01-20  110.0
7         108  Emma    NaN     C           None             NaN    NaN

In [62]:
# Create a an email pattern and then check whether the emails in the column match it
email_pattern = r"^[\w\.-]+@[\w\.-]+\.\w+$"

df[~df["email"].str.match(email_pattern, na=False)]

   student_id  name    age grade          email enrollment_date  score
2         103  John   -5.0     C  johnemail.com      not a date   75.0
5         106        130.0     Z       no_email      2025-01-20  110.0
7         108  Emma    NaN     C           None                    NaN

7 Validate date format

To validate the date format you need to use the pandas function of pd.to_datetime(), to change that column into a date time column. Then you can look in the data frame if there are any missing values.

In [63]:
# Convert the date column into a datetime type
valid_df['enrollment_date'] = pd.to_datetime(valid_df['enrollment_date'], errors = "coerce") # Note the "errors = "coerce"" turn the invalid dates into na
# Check the Data Frame
valid_df

   student_id   name    age grade            email enrollment_date  score
0         101   Alex   20.0     A   alex@email.com      2024-01-10   88.0
1         102  Maria   22.0     B  maria@email.com      2024-02-15   92.0
2         103   John   -5.0     C    johnemail.com             NaT   75.0
3         104  Sarah   19.0     A  sarah@email.com      2024-03-01   95.0
4         104  Sarah   19.0     A  sarah@email.com      2024-03-01   95.0
5         106    NaN  130.0     Z         no_email      2025-01-20  110.0
6         107  David   21.0     B  david@email.com      2024-04-12  -10.0
7         108   Emma    NaN     C             None             NaT    NaN

In [64]:
# Check the dates column to see if there are any NA
valid_df[valid_df['enrollment_date'].isna()]

   student_id  name  age grade          email enrollment_date  score
2         103  John -5.0     C  johnemail.com             NaT   75.0
7         108  Emma  NaN     C           None             NaT    NaN

8 Check Data Types 

Checking the data types of the dataframe simply just needs the fucntion of .dtypes()

In [65]:
# Check the data types in the data frame
valid_df.dtypes

student_id                  int64
name                       object
age                       float64
grade                      object
email                      object
enrollment_date    datetime64[ns]
score                     float64
dtype: object

In [66]:
# Another option for checking the data types
valid_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   student_id       8 non-null      int64
 1   name             7 non-null      object
 2   age              7 non-null      float64
 3   grade            8 non-null      object
 4   email            7 non-null      object
 5   enrollment_date  6 non-null      datetime64[ns]
 6   score            7 non-null      float64
dtypes: datetime64[ns](1), float64(2), int64(1), object(3)
memory usage: 580.0+ bytes

9 Check unique values

Looking for unique values allows to see whether there could be unexpected values in the dataframe or column

In [67]:
# Check if there are unique values in the data frame
uni = valid_df['grade'].unique()

# Get a count for each of the values
count = valid_df['grade'].value_counts(dropna = False)

# Check the variables
uni, count

(array(['A', 'B', 'C', 'Z'], dtype=object),
 grade
 A    3
 B    2
 C    2
 Z    1
 Name: count, dtype: int64)

10 Create validation flags

Ceating this validation flags essentially creates rules by creating ne columns for each row would either True or False, and the Falses are the ones to be looking at. This is done by creating columns for the previous methods

In [68]:
# Create a new copy of dataframe
valid_df2 = df.copy()

In [69]:
# Create a validation flags that flags, the valid age, valid score, valid grade, and then the valid email
valid_df2["valid_age"] = valid_df2["age"].between(0, 120)
valid_df2["valid_score"] = valid_df2["score"].between(0, 100)
valid_df2["valid_grade"] = valid_df2["grade"].isin(valid_grade)
valid_df2["valid_email"] = valid_df2["email"].str.match(email_pattern, na=False)

# Check the data frame 
valid_df2

,student_id,name,age,grade,email,enrollment_date,score,valid_age,valid_score,valid_grade,valid_email
0,101,Alex,20.0,A,alex@email.com,2024-01-10,88.0,True,True,True,True
1,102,Maria,22.0,B,maria@email.com,2024-02-15,92.0,True,True,True,True
2,103,John,-5.0,C,johnemail.com,not a date,75.0,False,True,True,False
3,104,Sarah,19.0,A,sarah@email.com,2024-03-01,95.0,True,True,True,True
4,104,Sarah,19.0,A,sarah@email.com,2024-03-01,95.0,True,True,True,True
5,106,,130.0,Z,no_email,2025-01-20,110.0,False,False,False,False
6,107,David,21.0,B,david@email.com,2024-04-12,-10.0,True,False,True,True
7,108,Emma,NaN,C,None,,NaN,False,False,True,False

11 Find rows that failed any validation rule

After creating validation flags and the new columns that are able to flag the columns, we can use filtering to focus on those rows that failed(False)

In [70]:
# Find the rows that failed the validation check
valid_df2[
    (valid_df2['valid_age'] == False) |
    (valid_df2['valid_score'] == False) |
    (valid_df2['valid_grade'] == False) |
    (valid_df2['valid_email'] == False)
]

,student_id,name,age,grade,email,enrollment_date,score,valid_age,valid_score,valid_grade,valid_email
2,103,John,-5.0,C,johnemail.com,not a date,75.0,False,True,True,False
5,106,,130.0,Z,no_email,2025-01-20,110.0,False,False,False,False
6,107,David,21.0,B,david@email.com,2024-04-12,-10.0,True,False,True,True
7,108,Emma,NaN,C,None,,NaN,False,False,True,False

12 Create a simple validation summary

Creating a validation summary allows to give a overview of the issues that are found within the dataframe.

In [71]:
# Create a new dataframe for validation summary
valid_summary = df.copy()
# Check thed data frame
valid_summary

   student_id   name    age grade            email enrollment_date  score
0         101   Alex   20.0     A   alex@email.com      2024-01-10   88.0
1         102  Maria   22.0     B  maria@email.com      2024-02-15   92.0
2         103   John   -5.0     C    johnemail.com      not a date   75.0
3         104  Sarah   19.0     A  sarah@email.com      2024-03-01   95.0
4         104  Sarah   19.0     A  sarah@email.com      2024-03-01   95.0
5         106         130.0     Z         no_email      2025-01-20  110.0
6         107  David   21.0     B  david@email.com      2024-04-12  -10.0
7         108   Emma    NaN     C             None                    NaN

In [72]:
# Create a validation summary of the dataframe
summary = pd.DataFrame({
    "Validation Check": [
        "Missing Values",
        "Duplicate student IDs",
        "Invalid ages",
        "Invalid scores",
        "Invalid grades",
        "Invalid emails",
        "Invalid dates"
    ],
    "number_of_issues": [
        df.isna().sum().sum(),
        df.duplicated(subset="student_id").sum(),
        ((df["age"] < 0) | (df["age"] > 120)).sum(),
        ((df["score"] < 0) | (df["score"] > 100)).sum(),
        (~df["grade"].isin(valid_grade)).sum(),
        (~df["email"].str.match(email_pattern, na=False)).sum(),
        df["enrollment_date"].isna().sum()
    ]
})

summary

        Validation Check  number_of_issues
0         Missing Values                 3
1  Duplicate student IDs                 1
2           Invalid ages                 2
3         Invalid scores                 2
4         Invalid grades                 1
5         Invalid emails                 3
6          Invalid dates                 0