Missing Values

by Josh Navarro

Goal: Learn the 3 ways to Handle Missing Data

Data: Asked Chatgpt to create me a dataframe to learn the three ways to handle missing data

In [2]:
# Import the neccessary libraries
import pandas as pd
import numpy as np

In [4]:
# Creating the the messy synthetic data
import pandas as pd
import numpy as np

data = {
    "Student": ["Alex", "Jordan", "Taylor", "Morgan", "Casey", "Riley"],
    "Math_Score": [85, np.nan, 78, 92, np.nan, 88],
    "English_Score": [90, 76, np.nan, 85, 80, np.nan],
    "Attendance_Rate": [0.95, 0.88, np.nan, 0.97, 0.91, np.nan]
}

df = pd.DataFrame(data)

df

  Student  Math_Score  English_Score  Attendance_Rate
0    Alex        85.0           90.0             0.95
1  Jordan         NaN           76.0             0.88
2  Taylor        78.0            NaN              NaN
3  Morgan        92.0           85.0             0.97
4   Casey         NaN           80.0             0.91
5   Riley        88.0            NaN              NaN

1 Dropping the NA

The first way to handle the missing data is just to drop it using the .dropNA() function

In [5]:
# See before using the .dropNA()
drop_df = df.copy()
drop_df.head()

  Student  Math_Score  English_Score  Attendance_Rate
0    Alex        85.0           90.0             0.95
1  Jordan         NaN           76.0             0.88
2  Taylor        78.0            NaN              NaN
3  Morgan        92.0           85.0             0.97
4   Casey         NaN           80.0             0.91

In [6]:
# Using the dropNA() to drop the NA 
# from the dataframe

drop_df = drop_df.dropna()
drop_df

  Student  Math_Score  English_Score  Attendance_Rate
0    Alex        85.0           90.0             0.95
3  Morgan        92.0           85.0             0.97

2 Fill the Numeric Values with a Median

The second way to handle the missing data is to fill in the numeric missing data with the median using the .fillna() function

In [7]:
# Create the fill_df as a copy of the df
# To show before
fill_df = df.copy()
fill_df.head()

  Student  Math_Score  English_Score  Attendance_Rate
0    Alex        85.0           90.0             0.95
1  Jordan         NaN           76.0             0.88
2  Taylor        78.0            NaN              NaN
3  Morgan        92.0           85.0             0.97
4   Casey         NaN           80.0             0.91

In [9]:
# Use the .fillna function
fill_df['Math_Score'] = fill_df['Math_Score'].fillna(fill_df['Math_Score'].median())
fill_df['English_Score'] = fill_df['English_Score'].fillna(fill_df['English_Score'].median())
fill_df['Attendance_Rate'] = fill_df['Attendance_Rate'].fillna(fill_df['Attendance_Rate'].median())

In [10]:
# The result after using the second method
fill_df

  Student  Math_Score  English_Score  Attendance_Rate
0    Alex        85.0           90.0             0.95
1  Jordan        86.5           76.0             0.88
2  Taylor        78.0           82.5             0.93
3  Morgan        92.0           85.0             0.97
4   Casey        86.5           80.0             0.91
5   Riley        88.0           82.5             0.93

3 Fill the string NAs with labels

The third way to get rid of the NAs is to fill them with labels. This is done also by using the .fillna() function.

In [11]:
# Create a new df that has strings for values
df2 = pd.DataFrame({
    "employee_id": [101, 102, 103, 104, 105, 106, 107, 108],
    "department": [
        "Sales",
        np.nan,
        "Finance",
        "HR",
        np.nan,
        "IT",
        "Marketing",
        np.nan
    ],
    "job_title": [
        "Analyst",
        "Manager",
        np.nan,
        "Coordinator",
        "Analyst",
        np.nan,
        "Director",
        "Manager"
    ],
    "employment_type": [
        "Full-Time",
        "Part-Time",
        np.nan,
        "Contract",
        "Full-Time",
        np.nan,
        "Intern",
        "Full-Time"
    ]
})

df2

   employee_id department    job_title employment_type
0          101      Sales      Analyst       Full-Time
1          102        NaN      Manager       Part-Time
2          103    Finance          NaN             NaN
3          104         HR  Coordinator        Contract
4          105        NaN      Analyst       Full-Time
5          106         IT          NaN             NaN
6          107  Marketing     Director          Intern
7          108        NaN      Manager       Full-Time

In [ ]:
string_df = df2.copy()
string_df.head()

   employee_id department    job_title employment_type
0          101      Sales      Analyst       Full-Time
1          102        NaN      Manager       Part-Time
2          103    Finance          NaN             NaN
3          104         HR  Coordinator        Contract
4          105        NaN      Analyst       Full-Time

In [15]:
string_df['department']

0        Sales
1          NaN
2      Finance
3           HR
4          NaN
5           IT
6    Marketing
7          NaN
Name: department, dtype: object

In [16]:
# Using the final method the replace the NA
string_df['department'] = string_df['department'].fillna("Not known")
string_df['job_title'] = string_df['job_title'].fillna("Not known")
string_df['employment_type'] = string_df['employment_type'].fillna("Not known")

In [17]:
# The result of the third method
string_df

   employee_id department    job_title employment_type
0          101      Sales      Analyst       Full-Time
1          102  Not known      Manager       Part-Time
2          103    Finance    Not known       Not known
3          104         HR  Coordinator        Contract
4          105  Not known      Analyst       Full-Time
5          106         IT    Not known       Not known
6          107  Marketing     Director          Intern
7          108  Not known      Manager       Full-Time