Missing Values
by Josh Navarro

Goal: Learn the 3 ways to Handle Missing Data

Data: Asked Chatgpt to create me a dataframe to learn the three ways to handle missing data

In [1]:
# Import the neccessary libraries
import pandas as pd
import numpy as np

In [2]:
# Creating the the messy synthetic data
import pandas as pd
import numpy as np

data = {
    "Student": ["Alex", "Jordan", "Taylor", "Morgan", "Casey", "Riley"],
    "Math_Score": [85, np.nan, 78, 92, np.nan, 88],
    "English_Score": [90, 76, np.nan, 85, 80, np.nan],
    "Attendance_Rate": [0.95, 0.88, np.nan, 0.97, 0.91, np.nan]
}

df = pd.DataFrame(data)

df

  Student  Math_Score  English_Score  Attendance_Rate
0    Alex        85.0           90.0             0.95
1  Jordan         NaN           76.0             0.88
2  Taylor        78.0            NaN              NaN
3  Morgan        92.0           85.0             0.97
4   Casey         NaN           80.0             0.91
5   Riley        88.0            NaN              NaN

1 Dropping the NA

The first way to handle the missing data is just to drop it using the .dropNA() function

In [ ]:
# See before using the .dropNA()
drop_df = df.copy()
drop_df.head()

  Student  Math_Score  English_Score  Attendance_Rate
0    Alex        85.0           90.0             0.95
1  Jordan         NaN           76.0             0.88
2  Taylor        78.0            NaN              NaN
3  Morgan        92.0           85.0             0.97
4   Casey         NaN           80.0             0.91

In [5]:
# Using the dropNA() to drop the NA 
# from the dataframe

drop_df = drop_df.dropna()
drop_df

  Student  Math_Score  English_Score  Attendance_Rate
0    Alex        85.0           90.0             0.95
3  Morgan        92.0           85.0             0.97

2 Fill the Numeric Values with a Median

The second way to handle the missing data is to fill in the numeric missing data with the median using the .fillna() function

In [ ]:
# Create the fill_df as a copy of the df
# To show before
fill_df = df.copy()
fill_df.head()

  Student  Math_Score  English_Score  Attendance_Rate
0    Alex        85.0           90.0             0.95
1  Jordan         NaN           76.0             0.88
2  Taylor        78.0            NaN              NaN
3  Morgan        92.0           85.0             0.97
4   Casey         NaN           80.0             0.91

In [ ]:
# Use the .fillna function

3 Fill the string NAs with labels

The third way to get rid of the NAs is to fill them with labels. This is done also by using the .fillna() function.