Cleaned_Exports

By: Josh Navarro

Goal: Learn how to export cleaned dataframes into different platforms

Data: Synthesized by ChatGPT

In [15]:
# Imports that are used
import pandas as pd
import numpy as np

In [16]:
df = pd.DataFrame({
    "employee_id": [101, 102, 103, 104, 105],
    "employee_name": ["John Smith", "Maria Lopez", "Kevin Brown", "Aisha Khan", "Daniel Lee"],
    "department": ["Sales", "Marketing", "IT", "Human Resources", "Finance"],
    "salary": [55000, 62000, 58000, 72000, 69000],
    "hire_date": pd.to_datetime(["2022-01-15", "2021-07-10", "2023-03-22", "2020-11-05", "2019-09-18"]),
    "full_time": [True, False, True, True, True]
})

df

   employee_id employee_name       department  salary  hire_date  full_time
0          101    John Smith            Sales   55000 2022-01-15       True
1          102   Maria Lopez        Marketing   62000 2021-07-10      False
2          103   Kevin Brown               IT   58000 2023-03-22       True
3          104    Aisha Khan  Human Resources   72000 2020-11-05       True
4          105    Daniel Lee          Finance   69000 2019-09-18       True

Checking befoe exporting

Need to check before exporting the dataframe to ensure that all of the data is in order. This is done by either .info() or .head()

In [17]:
# Create a copy of the data frame
export_df = df.copy()

In [18]:
# Use the .info()
export_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   employee_id    5 non-null      int64
 1   employee_name  5 non-null      object
 2   department     5 non-null      object
 3   salary         5 non-null      int64
 4   hire_date      5 non-null      datetime64[ns]
 5   full_time      5 non-null      bool
dtypes: bool(1), datetime64[ns](1), int64(2), object(2)
memory usage: 337.0+ bytes

In [19]:
# Use the .head()
export_df.head()

   employee_id employee_name       department  salary  hire_date  full_time
0          101    John Smith            Sales   55000 2022-01-15       True
1          102   Maria Lopez        Marketing   62000 2021-07-10      False
2          103   Kevin Brown               IT   58000 2023-03-22       True
3          104    Aisha Khan  Human Resources   72000 2020-11-05       True
4          105    Daniel Lee          Finance   69000 2019-09-18       True

Exporting the cleaned Data Frames

1 Export to CSV

In [20]:
# Export the data frame to csv
export_df.to_csv("cleaned_employee_data.csv", index=False)

2 Export to Excel

In [21]:
# Export the dataframe to Excel
export_df.to_excel("cleaned_employee_data.xlsx", index=False)

3 Export to JSON

In [22]:
# Export the dataframe to JSON
export_df.to_json("cleaned_employee_data.json", orient="records", indent=4)

4 Export to Parquet

In [23]:
# Export the data into Parquet
export_df.to_parquet("cleaned_employee_data.parquet", index=False)

5 Export selected columns only

In [24]:
# Create a list of selected columns_df
selected_cols = export_df[["employee_id", "employee_name", "department", "salary"]]
# Export the selected colums df into csv
selected_cols.to_csv("employee_summary.csv", index = False)

6 Export filtered data only

In [25]:
# Use boolean masking to filter the dataframe
full_time_df = export_df[export_df["full_time"] == True]
# Export the saved dataframe into the CSV
full_time_df.to_csv("full_time_employees.csv", index=False)

7 Export Sorted Data

In [26]:
# Sort the dataframe by the sales column
sorted_df = export_df.sort_values(by="salary", ascending=False)
# Export the sorted dataframe into csv
sorted_df.to_csv("employees_sorted_by_salary.csv", index=False)

8 Export with cleaned data formatting

In [27]:
# Create a formatted date colunmn
export_df["hire_date_clean"] = export_df["hire_date"].dt.strftime("%Y-%m-%d")
# Saved the formated the dataframe to csv
export_df.to_csv("cleaned_employee_data_dates.csv", index=False)