Filtering and Sorting
by: Josh Navarro

Goal: Learn the methods of filtering and sorting in python pandas.
Data: Synthetic that is created by ChatGPT

In [1]:
# Imports that we are gonna be using
import pandas as pd
import numpy as np

In [2]:
# Creating the fake data 
import pandas as pd

data = pd.DataFrame({
    "student": ["Alex", "Bella", "Chris", "Diana", "Ethan", "Fiona", "George", "Hannah", "Ivan", "Jasmine"],
    "major": ["CS", "Business", "CS", "Nursing", "Business", "CS", "Nursing", "Business", "CS", "Nursing"],
    "grade_level": ["Freshman", "Sophomore", "Junior", "Senior", "Freshman", "Senior", "Junior", "Sophomore", "Freshman", "Senior"],
    "exam_score": [88, 72, 95, 64, 81, 90, 58, 76, 69, 84],
    "attendance": [92, 85, 98, 70, 88, 95, 60, 80, 75, 91],
    "hours_studied": [6, 3, 9, 2, 5, 8, 1, 4, 3, 7],
    "passed": [True, True, True, False, True, True, False, True, True, True]
})

data

,student,major,grade_level,exam_score,attendance,hours_studied,passed
0,Alex,CS,Freshman,88,92,6,True
1,Bella,Business,Sophomore,72,85,3,True
2,Chris,CS,Junior,95,98,9,True
3,Diana,Nursing,Senior,64,70,2,False
4,Ethan,Business,Freshman,81,88,5,True
5,Fiona,CS,Senior,90,95,8,True
6,George,Nursing,Junior,58,60,1,False
7,Hannah,Business,Sophomore,76,80,4,True
8,Ivan,CS,Freshman,69,75,3,True
9,Jasmine,Nursing,Senior,84,91,7,True

Filtering Methods

In [6]:
# Copying the data into a seperate data frame
filter_df = data.copy()
# Check the data
filter_df.head()

  student     major grade_level  exam_score  attendance  hours_studied  passed
0    Alex        CS    Freshman          88          92              6    True
1   Bella  Business   Sophomore          72          85              3    True
2   Chris        CS      Junior          95          98              9    True
3   Diana   Nursing      Senior          64          70              2   False
4   Ethan  Business    Freshman          81          88              5    True

Filtering using 1 Condition

Using only 1 condition to filter out from a column

In [8]:
# Going to filter 
# on students that have an exam 
# score of more than 75

more_than_75 = filter_df[filter_df['exam_score'] > 75]
more_than_75

,student,major,grade_level,exam_score,attendance,hours_studied,passed
0,Alex,CS,Freshman,88,92,6,True
2,Chris,CS,Junior,95,98,9,True
4,Ethan,Business,Freshman,81,88,5,True
5,Fiona,CS,Senior,90,95,8,True
7,Hannah,Business,Sophomore,76,80,4,True
9,Jasmine,Nursing,Senior,84,91,7,True

Filtering mutiple conditions using &

Using multple condition on the same column or different you need to use the ampersand to link the filtering conditions togther.

In [ ]:
# We are gonna filter by students that have an exam 
# score less than or equal to 60 
# and their attendance is below 55

less_60_below_55 = filter_df[(filter_df['exam_score'] <= 75) & (filter_df['attendance'] < 80)]
less_60_below_55

  student    major grade_level  exam_score  attendance  hours_studied  passed
3   Diana  Nursing      Senior          64          70              2   False
6  George  Nursing      Junior          58          60              1   False
8    Ivan       CS    Freshman          69          75              3    True

Filter using the | for the OR

Filter using the |(OR) allows the condition to be either one or the other.

In [ ]:
# We want to filerwhether a student 
# has an example score of above 85 
# or they studied for 5 hours

or_method = filter_df[(filter_df['exam_score'] > 85) | (filter_df['hours_studied'] > 5)]
or_method

   student    major grade_level  exam_score  attendance  hours_studied  passed
0     Alex       CS    Freshman          88          92              6    True
2    Chris       CS      Junior          95          98              9    True
5    Fiona       CS      Senior          90          95              8    True
9  Jasmine  Nursing      Senior          84          91              7    True

Filter using the !=

Using the != to filter out a specific value in the dataframe

In [19]:
# Filtering for the student who did not pass

not_method = filter_df[filter_df['passed'] != True]
not_method

  student    major grade_level  exam_score  attendance  hours_studied  passed
3   Diana  Nursing      Senior          64          70              2   False
6  George  Nursing      Junior          58          60              1   False

Filter using the function of .isin()

Using the .isin() functions takes a list and checks whether values in the list are in the column that you specified.

In [28]:
# Filtering to see whether students are in Nursing

isin_method = filter_df[filter_df['major'].isin(["Nursing"])]
isin_method

   student    major grade_level  exam_score  attendance  hours_studied  passed
3    Diana  Nursing      Senior          64          70              2   False
6   George  Nursing      Junior          58          60              1   False
9  Jasmine  Nursing      Senior          84          91              7    True

Filter using the function of .between()

Using the .between() function takes two values and filters all of the rows between those values, will most likely be a numerical value.

In [32]:
# Filtering to find the students exam score
# that are between the values of 65 and 85

between_method = filter_df[filter_df['exam_score'].between(65, 85)]
between_method

,student,major,grade_level,exam_score,attendance,hours_studied,passed
1,Bella,Business,Sophomore,72,85,3,True
4,Ethan,Business,Freshman,81,88,5,True
7,Hannah,Business,Sophomore,76,80,4,True
8,Ivan,CS,Freshman,69,75,3,True
9,Jasmine,Nursing,Senior,84,91,7,True

Filter using the string methods, using str.startswith()

Filtering string columns using the .str.startswith() allows to check columns that have a string value and find whether they start with something

In [34]:
# Finding Students names that start with the letter B

start_method = filter_df[filter_df['student'].str.startswith("B")]
start_method

  student     major grade_level  exam_score  attendance  hours_studied  passed
1   Bella  Business   Sophomore          72          85              3    True

Filter using the .query() function

Another way to query, and filter the dataframe, it is preference but may sometimes look cleaner

In [39]:
# Filter the students that have the exam score of 
# more than 80 and attendance more than 90

query_method = filter_df.query("exam_score >= 80 and attendance >= 90")
query_method

   student    major grade_level  exam_score  attendance  hours_studied  passed
0     Alex       CS    Freshman          88          92              6    True
2    Chris       CS      Junior          95          98              9    True
5    Fiona       CS      Senior          90          95              8    True
9  Jasmine  Nursing      Senior          84          91              7    True

Sorting Methods

Sorting by one column

Sorting the columns by decending

Sorting by the multiple columns

Sort multiple columns with different directions

Sort by index

Resetting the index after sorting