Duplicates
By: Josh Navarro

Goal: Learn the ways to handle duplicates in python pandas
Data: Synthesized by chatgpt

In [20]:
# Imports for this notebook
import pandas as pd
import numpy as np

In [21]:
# Synthetic data created by chatgpt
import pandas as pd

df = pd.DataFrame({
    "student_id": [101, 102, 103, 103, 104, 105, 106, 106, 107, 108, 108],
    "name": [
        "Alex", "Maria", "James", "James",
        "Sofia", "Daniel", "Emma", "Emma",
        "Chris", "Mia", "Mia"
    ],
    "course": [
        "Python", "SQL", "Excel", "Excel",
        "Tableau", "Python", "SQL", "SQL",
        "Excel", "Python", "Python"
    ],
    "score": [88, 92, 75, 75, 85, 90, 79, 79, 84, 91, 95],
    "signup_date": [
        "2026-01-05", "2026-01-06", "2026-01-07", "2026-01-07",
        "2026-01-08", "2026-01-09", "2026-01-10", "2026-01-10",
        "2026-01-11", "2026-01-12", "2026-01-12"
    ]
})

df

    student_id    name   course  score signup_date
0          101    Alex   Python     88  2026-01-05
1          102   Maria      SQL     92  2026-01-06
2          103   James    Excel     75  2026-01-07
3          103   James    Excel     75  2026-01-07
4          104   Sofia  Tableau     85  2026-01-08
5          105  Daniel   Python     90  2026-01-09
6          106    Emma      SQL     79  2026-01-10
7          106    Emma      SQL     79  2026-01-10
8          107   Chris    Excel     84  2026-01-11
9          108     Mia   Python     91  2026-01-12
10         108     Mia   Python     95  2026-01-12

What are the actions you can do when you deal with duplicates in the data frame

In [22]:
# Create a copy of the data frame to use

dupi_df = df.copy()

Check if there are any duplicates in the dataframe

You are able to check if there are any duplicates in this dataframe by using the function .duplicated() and .sum()

In [23]:
# Check how many duplicates there are in the dataframe
dupi_df.duplicated().sum()

np.int64(2)

Checking how many times a value shows up in the dataframe to find which are duplicated

You can count the amount of values in a column by using the function .value_counts()

In [24]:
dupi_df['student_id'].value_counts()

student_id
103    2
106    2
108    2
101    1
104    1
102    1
105    1
107    1
Name: count, dtype: int64

Then we need to find where the duplicates are located in dateframe

We are able to find where the duplicates are gonna be located by using the .duplicated() function

In [25]:
# Finding the exact location of where the duplicates are
dupi_df[dupi_df.duplicated()]

   student_id   name course  score signup_date
3         103  James  Excel     75  2026-01-07
7         106   Emma    SQL     79  2026-01-10

If we want to include the first of the duplicates as well we can use the keep argument to equal False

In [26]:
# Finding the duplicates and the first occurance as well
dupi_df[dupi_df.duplicated(keep=False)]

   student_id   name course  score signup_date
2         103  James  Excel     75  2026-01-07
3         103  James  Excel     75  2026-01-07
6         106   Emma    SQL     79  2026-01-10
7         106   Emma    SQL     79  2026-01-10

Next we have to remove the duplicates

We can do this in multiple different ways, how it is done depends on what you need done

1 We can just all of the exact rows that are duplicates that are identical

Dropping all of the exact rows that are duplicates you need to use the function .drop_duplcates()

In [27]:
# Use the .drop_duplicates to remove all of the duplicates
dupi_df.drop_duplicates()

    student_id    name   course  score signup_date
0          101    Alex   Python     88  2026-01-05
1          102   Maria      SQL     92  2026-01-06
2          103   James    Excel     75  2026-01-07
4          104   Sofia  Tableau     85  2026-01-08
5          105  Daniel   Python     90  2026-01-09
6          106    Emma      SQL     79  2026-01-10
8          107   Chris    Excel     84  2026-01-11
9          108     Mia   Python     91  2026-01-12
10         108     Mia   Python     95  2026-01-12

Dropping by a singular coplumn or mulitple columns

Dropping by specific columns is done by using the drop_duplicates function but you pass the subset of either a column name or a list of column names

In [28]:
dupi_df.drop_duplicates(subset = "student_id")

   student_id    name   course  score signup_date
0         101    Alex   Python     88  2026-01-05
1         102   Maria      SQL     92  2026-01-06
2         103   James    Excel     75  2026-01-07
4         104   Sofia  Tableau     85  2026-01-08
5         105  Daniel   Python     90  2026-01-09
6         106    Emma      SQL     79  2026-01-10
8         107   Chris    Excel     84  2026-01-11
9         108     Mia   Python     91  2026-01-12

Keep the last duplicate instead of the first

This is done by passing in another argument in the function of .drop_duplicates(), the argument is keep where it will equal "last"

In [29]:
# Dropping the duplicates in the student_id column
# but keeping the last insetead of the first
dupi_df.drop_duplicates(subset = "student_id", keep = False)

   student_id    name   course  score signup_date
0         101    Alex   Python     88  2026-01-05
1         102   Maria      SQL     92  2026-01-06
4         104   Sofia  Tableau     85  2026-01-08
5         105  Daniel   Python     90  2026-01-09
8         107   Chris    Excel     84  2026-01-11