Date Cleaning

By: Josh Navarro

Goal: Learn how to clean dates in a data frame using python pandas

Data: Created by ChatGPT

In [4]:
# Imports that will be used
import pandas as pd
import numpy as np

In [5]:
# Create the synthetic data 
df = pd.DataFrame({
    "employee_id": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "name": ["Alex", "Brianna", "Chris", "Diana", "Ethan", "Fatima", "George", "Hannah", "Ivan", "Julia"],
    "hire_date": [
        "2023-01-15",     
        "01/20/2023",     
        "March 5, 2023",  
        "2023/04/10",     
        "05-12-2023",     
        "20230601",      
        "not available",  
        "",               
        None,            
        "2023-13-01"      
    ],
    "last_review_date": [
        "2024-01-10",
        "2/15/2024",
        "April 20 2024",
        "2024.05.01",
        "06-10-2024",
        "20240715",
        "missing",
        "",
        None,
        "2024-02-30"     
    ]
})

df

   employee_id     name      hire_date last_review_date
0          101     Alex     2023-01-15       2024-01-10
1          102  Brianna     01/20/2023        2/15/2024
2          103    Chris  March 5, 2023    April 20 2024
3          104    Diana     2023/04/10       2024.05.01
4          105    Ethan     05-12-2023       06-10-2024
5          106   Fatima       20230601         20240715
6          107   George  not available          missing
7          108   Hannah
8          109     Ivan           None             None
9          110    Julia     2023-13-01       2024-02-30

Cleaning Dates in Python Pandas

There are many methods that are done to clean dates.

In [6]:
# Create a copy of the data
date_df = df.copy()
# Check the data
date_df.head()

   employee_id     name      hire_date last_review_date
0          101     Alex     2023-01-15       2024-01-10
1          102  Brianna     01/20/2023        2/15/2024
2          103    Chris  March 5, 2023    April 20 2024
3          104    Diana     2023/04/10       2024.05.01
4          105    Ethan     05-12-2023       06-10-2024

1 Converting into real datetime columns

To convert a column into a date time column you have to use the to_datetime() function. Note use errors = "coerce" if the date is invalid then it will become NaT

In [7]:
# Check the data types
date_df.dtypes

employee_id          int64
name                object
hire_date           object
last_review_date    object
dtype: object

In [8]:
# Change both of the columns hire_date and the last_reivew_date
# into actual date time columns
date_df["hire_date_clean"] = pd.to_datetime(
    date_df['hire_date'],
    errors = 'coerce'
)

date_df['last_review_date_clean'] = pd.to_datetime(
    date_df['last_review_date'],
    errors = 'coerce'
)

# Check the dataframe
date_df.head()

,employee_id,name,hire_date,last_review_date,hire_date_clean,last_review_date_clean
0,101,Alex,2023-01-15,2024-01-10,2023-01-15,2024-01-10
1,102,Brianna,01/20/2023,2/15/2024,NaT,NaT
2,103,Chris,"March 5, 2023",April 20 2024,NaT,NaT
3,104,Diana,2023/04/10,2024.05.01,NaT,NaT
4,105,Ethan,05-12-2023,06-10-2024,NaT,NaT

2 Check the dates that couldnt be converted

A continuation of the previous method, you can check the methods that were not converted correctly by using the isna() function

In [9]:
# Check the hire_date_clean 
# columnto see if there are NA
date_df[date_df["hire_date_clean"].isna()]

,employee_id,name,hire_date,last_review_date,hire_date_clean,last_review_date_clean
1,102,Brianna,01/20/2023,2/15/2024,NaT,NaT
2,103,Chris,"March 5, 2023",April 20 2024,NaT,NaT
3,104,Diana,2023/04/10,2024.05.01,NaT,NaT
4,105,Ethan,05-12-2023,06-10-2024,NaT,NaT
5,106,Fatima,20230601,20240715,NaT,NaT
6,107,George,not available,missing,NaT,NaT
7,108,Hannah,,,NaT,NaT
8,109,Ivan,None,None,NaT,NaT
9,110,Julia,2023-13-01,2024-02-30,NaT,NaT

In [10]:
# Do the same for the last_review_date_clean
date_df[date_df['last_review_date_clean'].isna()]

,employee_id,name,hire_date,last_review_date,hire_date_clean,last_review_date_clean
1,102,Brianna,01/20/2023,2/15/2024,NaT,NaT
2,103,Chris,"March 5, 2023",April 20 2024,NaT,NaT
3,104,Diana,2023/04/10,2024.05.01,NaT,NaT
4,105,Ethan,05-12-2023,06-10-2024,NaT,NaT
5,106,Fatima,20230601,20240715,NaT,NaT
6,107,George,not available,missing,NaT,NaT
7,108,Hannah,,,NaT,NaT
8,109,Ivan,None,None,NaT,NaT
9,110,Julia,2023-13-01,2024-02-30,NaT,NaT

3 Replacing the bad dates text before converting

Before converting the columns into a date time column you can replace the text values in columns and then you can convert and you can do this with the .replace()

In [11]:
# Copy a new data frame
date_df = df.copy()
# Check the dataframe
date_df.head()

   employee_id     name      hire_date last_review_date
0          101     Alex     2023-01-15       2024-01-10
1          102  Brianna     01/20/2023        2/15/2024
2          103    Chris  March 5, 2023    April 20 2024
3          104    Diana     2023/04/10       2024.05.01
4          105    Ethan     05-12-2023       06-10-2024

In [12]:
# Replace the the words missing, etc into NA
date_df["hire_date"] = date_df["hire_date"].replace(
    ["not available", "", "missing"],
    np.nan
)

date_df["last_review_date"] = date_df["last_review_date"].replace(
    ["not available", "", "missing"],
    np.nan
)

In [13]:
# Convert the hire_date and the last_review_date 
# columns into the date time column
date_df["hire_date_clean"] = pd.to_datetime(
    date_df["hire_date"],
    errors="coerce"
)

date_df["last_review_date_clean"] = pd.to_datetime(
    date_df["last_review_date"],
    errors="coerce"
)

# Check the data frame
date_df

,employee_id,name,hire_date,last_review_date,hire_date_clean,last_review_date_clean
0,101,Alex,2023-01-15,2024-01-10,2023-01-15,2024-01-10
1,102,Brianna,01/20/2023,2/15/2024,NaT,NaT
2,103,Chris,"March 5, 2023",April 20 2024,NaT,NaT
3,104,Diana,2023/04/10,2024.05.01,NaT,NaT
4,105,Ethan,05-12-2023,06-10-2024,NaT,NaT
5,106,Fatima,20230601,20240715,NaT,NaT
6,107,George,NaN,NaN,NaT,NaT
7,108,Hannah,NaN,NaN,NaT,NaT
8,109,Ivan,None,None,NaT,NaT
9,110,Julia,2023-13-01,2024-02-30,NaT,NaT

4 Use a specific date format, when knowing the pattern

Transforming the values in the column you are able to use the to_datetime function, with the second argument being format="%Y-%m-%d" or any format that you would want depending on what you need.

In [14]:
# Some examples of this

# Changes this format into date time
(
pd.to_datetime("2024-07-15", format="%Y-%m-%d"),
pd.to_datetime("July 15, 2024", format="%B %d, %Y"),
pd.to_datetime("07/15/2024", format="%m/%d/%Y")

)

(Timestamp('2024-07-15 00:00:00'),
 Timestamp('2024-07-15 00:00:00'),
 Timestamp('2024-07-15 00:00:00'))

5 Extracting part of the date 

Once the columns or the columns are converted into a date time columns, then you can also extract part of the date. Using .dt.year, .dt.month, etc

In [15]:
# Extrract the year and the month from the hire_date_column

date_df['hire_year'] =  date_df['hire_date_clean'].dt.year
date_df['hire_month'] = date_df['hire_date_clean'].dt.month

# Check the data frame
date_df

,employee_id,name,hire_date,last_review_date,hire_date_clean,last_review_date_clean,hire_year,hire_month
0,101,Alex,2023-01-15,2024-01-10,2023-01-15,2024-01-10,2023.0,1.0
1,102,Brianna,01/20/2023,2/15/2024,NaT,NaT,NaN,NaN
2,103,Chris,"March 5, 2023",April 20 2024,NaT,NaT,NaN,NaN
3,104,Diana,2023/04/10,2024.05.01,NaT,NaT,NaN,NaN
4,105,Ethan,05-12-2023,06-10-2024,NaT,NaT,NaN,NaN
5,106,Fatima,20230601,20240715,NaT,NaT,NaN,NaN
6,107,George,NaN,NaN,NaT,NaT,NaN,NaN
7,108,Hannah,NaN,NaN,NaT,NaT,NaN,NaN
8,109,Ivan,None,None,NaT,NaT,NaN,NaN
9,110,Julia,2023-13-01,2024-02-30,NaT,NaT,NaN,NaN

6 Calculate time difference between the dates

Calculating the time difference between the dates is done by having two columns that are date time columns and then just subtracting them

In [16]:
# Create a column that has the days 
# until the review from the hire date

date_df["days_until_review"] = (
    date_df["last_review_date_clean"] - date_df["hire_date_clean"]
).dt.days

# Check thae data frame
date_df

,employee_id,name,hire_date,last_review_date,hire_date_clean,last_review_date_clean,hire_year,hire_month,days_until_review
0,101,Alex,2023-01-15,2024-01-10,2023-01-15,2024-01-10,2023.0,1.0,360.0
1,102,Brianna,01/20/2023,2/15/2024,NaT,NaT,NaN,NaN,NaN
2,103,Chris,"March 5, 2023",April 20 2024,NaT,NaT,NaN,NaN,NaN
3,104,Diana,2023/04/10,2024.05.01,NaT,NaT,NaN,NaN,NaN
4,105,Ethan,05-12-2023,06-10-2024,NaT,NaT,NaN,NaN,NaN
5,106,Fatima,20230601,20240715,NaT,NaT,NaN,NaN,NaN
6,107,George,NaN,NaN,NaT,NaT,NaN,NaN,NaN
7,108,Hannah,NaN,NaN,NaT,NaT,NaN,NaN,NaN
8,109,Ivan,None,None,NaT,NaT,NaN,NaN,NaN
9,110,Julia,2023-13-01,2024-02-30,NaT,NaT,NaN,NaN,NaN

7 Fill the missing dates

Another method that can be done is filling the missing dates with a default value, whether that already be a predetermined date or use another column and using the function of .fillna()

In [17]:
# Fill in the hire_date with the 
# predetermined date of 01-01-2000
date_df['hire_date_filled'] = date_df['hire_date_clean'].fillna(
    pd.Timestamp("01-01-2000")
)

# Fill in another column using the last_review_date column
date_df["hire_date_filled2"] = date_df["hire_date_clean"].fillna(
    date_df["last_review_date_clean"]
)

# Check the dataframe
date_df

,employee_id,name,hire_date,last_review_date,hire_date_clean,last_review_date_clean,hire_year,hire_month,days_until_review,hire_date_filled,hire_date_filled2
0,101,Alex,2023-01-15,2024-01-10,2023-01-15,2024-01-10,2023.0,1.0,360.0,2023-01-15,2023-01-15
1,102,Brianna,01/20/2023,2/15/2024,NaT,NaT,NaN,NaN,NaN,2000-01-01,NaT
2,103,Chris,"March 5, 2023",April 20 2024,NaT,NaT,NaN,NaN,NaN,2000-01-01,NaT
3,104,Diana,2023/04/10,2024.05.01,NaT,NaT,NaN,NaN,NaN,2000-01-01,NaT
4,105,Ethan,05-12-2023,06-10-2024,NaT,NaT,NaN,NaN,NaN,2000-01-01,NaT
5,106,Fatima,20230601,20240715,NaT,NaT,NaN,NaN,NaN,2000-01-01,NaT
6,107,George,NaN,NaN,NaT,NaT,NaN,NaN,NaN,2000-01-01,NaT
7,108,Hannah,NaN,NaN,NaT,NaT,NaN,NaN,NaN,2000-01-01,NaT
8,109,Ivan,None,None,NaT,NaT,NaN,NaN,NaN,2000-01-01,NaT
9,110,Julia,2023-13-01,2024-02-30,NaT,NaT,NaN,NaN,NaN,2000-01-01,NaT

8 Filter rows by the dates

Filtering through the dates need a column that is a date time, and then just regular filtering, bt either using query or by the boolean masking

In [18]:
# Filter the hire_date_clean that is more than the date of 2023-03-01
date_df[date_df["hire_date_clean"] >= "2023-03-01"]

# Filter the hire_date_clean column between the 2023-01-01 date, and then the 2023-06-30 date
date_df[
    (date_df["hire_date_clean"] >= "2023-01-01") &
    (date_df["hire_date_clean"] <= "2023-06-30")
]

,employee_id,name,hire_date,last_review_date,hire_date_clean,last_review_date_clean,hire_year,hire_month,days_until_review,hire_date_filled,hire_date_filled2
0,101,Alex,2023-01-15,2024-01-10,2023-01-15,2024-01-10,2023.0,1.0,360.0,2023-01-15,2023-01-15

9 Sort by dates

Sorting by the by the date uses the function .sort_values you just need to make sure that the column that you are sorting of the datetime type

In [19]:
# Sort the dataframe by the hire_date_clean column in ascending order
date_df.sort_values("hire_date_clean")

,employee_id,name,hire_date,last_review_date,hire_date_clean,last_review_date_clean,hire_year,hire_month,days_until_review,hire_date_filled,hire_date_filled2
0,101,Alex,2023-01-15,2024-01-10,2023-01-15,2024-01-10,2023.0,1.0,360.0,2023-01-15,2023-01-15
1,102,Brianna,01/20/2023,2/15/2024,NaT,NaT,NaN,NaN,NaN,2000-01-01,NaT
2,103,Chris,"March 5, 2023",April 20 2024,NaT,NaT,NaN,NaN,NaN,2000-01-01,NaT
3,104,Diana,2023/04/10,2024.05.01,NaT,NaT,NaN,NaN,NaN,2000-01-01,NaT
4,105,Ethan,05-12-2023,06-10-2024,NaT,NaT,NaN,NaN,NaN,2000-01-01,NaT
5,106,Fatima,20230601,20240715,NaT,NaT,NaN,NaN,NaN,2000-01-01,NaT
6,107,George,NaN,NaN,NaT,NaT,NaN,NaN,NaN,2000-01-01,NaT
7,108,Hannah,NaN,NaN,NaT,NaT,NaN,NaN,NaN,2000-01-01,NaT
8,109,Ivan,None,None,NaT,NaT,NaN,NaN,NaN,2000-01-01,NaT
9,110,Julia,2023-13-01,2024-02-30,NaT,NaT,NaN,NaN,NaN,2000-01-01,NaT

In [20]:
# Sort by the dataframe by the hire_date_clean column in descending order
date_df.sort_values("hire_date_clean", ascending = False)

,employee_id,name,hire_date,last_review_date,hire_date_clean,last_review_date_clean,hire_year,hire_month,days_until_review,hire_date_filled,hire_date_filled2
0,101,Alex,2023-01-15,2024-01-10,2023-01-15,2024-01-10,2023.0,1.0,360.0,2023-01-15,2023-01-15
1,102,Brianna,01/20/2023,2/15/2024,NaT,NaT,NaN,NaN,NaN,2000-01-01,NaT
2,103,Chris,"March 5, 2023",April 20 2024,NaT,NaT,NaN,NaN,NaN,2000-01-01,NaT
3,104,Diana,2023/04/10,2024.05.01,NaT,NaT,NaN,NaN,NaN,2000-01-01,NaT
4,105,Ethan,05-12-2023,06-10-2024,NaT,NaT,NaN,NaN,NaN,2000-01-01,NaT
5,106,Fatima,20230601,20240715,NaT,NaT,NaN,NaN,NaN,2000-01-01,NaT
6,107,George,NaN,NaN,NaT,NaT,NaN,NaN,NaN,2000-01-01,NaT
7,108,Hannah,NaN,NaN,NaT,NaT,NaN,NaN,NaN,2000-01-01,NaT
8,109,Ivan,None,None,NaT,NaT,NaN,NaN,NaN,2000-01-01,NaT
9,110,Julia,2023-13-01,2024-02-30,NaT,NaT,NaN,NaN,NaN,2000-01-01,NaT