Text Cleaning

By: Josh Navarro

Goal: Learn how apply text cleaning in Jupyter Notebook using the python pandas

Data: Synthesized by ChatGpt

In [2]:
# Imports that we are going to be using
import pandas as pd
import numpy as np

In [3]:
# Synthetic Data created by ChatGPT
df = pd.DataFrame({
    "customer_id": [101, 102, 103, 104, 105, 106, 107, 108],
    "name": [
        "  alex johnson ",
        "MARIA   GARCIA",
        "James-smith",
        "sofia o'neill",
        "DANIEL  lee ",
        " emma_watson",
        "Chris Brown  ",
        "mia   davis"
    ],
    "email": [
        " ALEX.JOHNSON@GMAIL.COM ",
        "maria_garcia@yahoo.com",
        "James.Smith@Outlook.COM",
        "sofia.oneill@gmail.com ",
        "daniel.lee@@gmail.com",
        "emma_watson@gmail",
        "chris.brown@hotmail.com",
        " mia.davis@gmail.com"
    ],
    "phone": [
        "(555) 123-4567",
        "555.987.6543",
        "555-222-3333",
        " 555 444 5555 ",
        "+1-555-777-8888",
        "phone: 5556669999",
        "N/A",
        "(555)-000-1111"
    ],
    "city": [
        " new york",
        "LOS ANGELES ",
        "San   Diego",
        "chicago",
        " HOUSTON",
        "phoenix!!!",
        "Dallas?",
        "san jose "
    ],
    "review": [
        "  Great product!!! ",
        "BAD service...",
        "okay-quality, not bad",
        "I LOVE this item!!!",
        "too expensive $$$",
        "would buy again :)",
        "N/A",
        "fast shipping--thanks!"
    ]
})

df

,customer_id,name,email,phone,city,review
0,101,alex johnson,ALEX.JOHNSON@GMAIL.COM,(555) 123-4567,new york,Great product!!!
1,102,MARIA GARCIA,maria_garcia@yahoo.com,555.987.6543,LOS ANGELES,BAD service...
2,103,James-smith,James.Smith@Outlook.COM,555-222-3333,San Diego,"okay-quality, not bad"
3,104,sofia o'neill,sofia.oneill@gmail.com,555 444 5555,chicago,I LOVE this item!!!
4,105,DANIEL lee,daniel.lee@@gmail.com,+1-555-777-8888,HOUSTON,too expensive $$$
5,106,emma_watson,emma_watson@gmail,phone: 5556669999,phoenix!!!,would buy again :)
6,107,Chris Brown,chris.brown@hotmail.com,N/A,Dallas?,N/A
7,108,mia davis,mia.davis@gmail.com,(555)-000-1111,san jose,fast shipping--thanks!

Cleaning Texts

There are many things that can be done to clean texts.

In [4]:
# Create a copy of the data frame
text_df = df.copy()
text_df.head()

,customer_id,name,email,phone,city,review
0,101,alex johnson,ALEX.JOHNSON@GMAIL.COM,(555) 123-4567,new york,Great product!!!
1,102,MARIA GARCIA,maria_garcia@yahoo.com,555.987.6543,LOS ANGELES,BAD service...
2,103,James-smith,James.Smith@Outlook.COM,555-222-3333,San Diego,"okay-quality, not bad"
3,104,sofia o'neill,sofia.oneill@gmail.com,555 444 5555,chicago,I LOVE this item!!!
4,105,DANIEL lee,daniel.lee@@gmail.com,+1-555-777-8888,HOUSTON,too expensive $$$

1 Remove the Spaces at the beginning and the end

Removing the spaces at the beginning and the end is possible by using the function of .str.strip() on a column

In [5]:
# Remove the end and beginning spaces for the columns name, email, and city
text_df['name'] = text_df['name'].str.strip()
text_df['email'] = text_df['email'].str.strip()
text_df['city'] = text_df['city'].str.strip()

# Check the new data frame
text_df.head()

,customer_id,name,email,phone,city,review
0,101,alex johnson,ALEX.JOHNSON@GMAIL.COM,(555) 123-4567,new york,Great product!!!
1,102,MARIA GARCIA,maria_garcia@yahoo.com,555.987.6543,LOS ANGELES,BAD service...
2,103,James-smith,James.Smith@Outlook.COM,555-222-3333,San Diego,"okay-quality, not bad"
3,104,sofia o'neill,sofia.oneill@gmail.com,555 444 5555,chicago,I LOVE this item!!!
4,105,DANIEL lee,daniel.lee@@gmail.com,+1-555-777-8888,HOUSTON,too expensive $$$

2 Change text to lowercase

Chaning the text values to lowercase is done by using fucntion str.lower() on that column

In [6]:
# Change both the name and the city to lower case

text_df['name'] = text_df['name'].str.lower()
text_df['email'] = text_df['email'].str.lower()

text_df.head()

,customer_id,name,email,phone,city,review
0,101,alex johnson,alex.johnson@gmail.com,(555) 123-4567,new york,Great product!!!
1,102,maria garcia,maria_garcia@yahoo.com,555.987.6543,LOS ANGELES,BAD service...
2,103,james-smith,james.smith@outlook.com,555-222-3333,San Diego,"okay-quality, not bad"
3,104,sofia o'neill,sofia.oneill@gmail.com,555 444 5555,chicago,I LOVE this item!!!
4,105,daniel lee,daniel.lee@@gmail.com,+1-555-777-8888,HOUSTON,too expensive $$$

3 Change text to title case

Changing the text to the title case is done by the function of .str.title()

In [7]:
# Change the names and the city columns into title case
text_df['name'] = text_df['name'].str.title()
text_df['city'] = text_df['city'].str.title()
# Check the dataframe
text_df.head()

,customer_id,name,email,phone,city,review
0,101,Alex Johnson,alex.johnson@gmail.com,(555) 123-4567,New York,Great product!!!
1,102,Maria Garcia,maria_garcia@yahoo.com,555.987.6543,Los Angeles,BAD service...
2,103,James-Smith,james.smith@outlook.com,555-222-3333,San Diego,"okay-quality, not bad"
3,104,Sofia O'Neill,sofia.oneill@gmail.com,555 444 5555,Chicago,I LOVE this item!!!
4,105,Daniel Lee,daniel.lee@@gmail.com,+1-555-777-8888,Houston,too expensive $$$

4 Raplace characters

In order to replace characters in a column that have text in it you need to use the function of .str.replace()

In [8]:
# Replace both the - and the _ in the names columns
text_df['name'] = (
    text_df['name']
    .str.replace("_"," ", regex=False)
    .str.replace("-", " ", regex=False)
)

# Check the data frame
text_df.head()

,customer_id,name,email,phone,city,review
0,101,Alex Johnson,alex.johnson@gmail.com,(555) 123-4567,New York,Great product!!!
1,102,Maria Garcia,maria_garcia@yahoo.com,555.987.6543,Los Angeles,BAD service...
2,103,James Smith,james.smith@outlook.com,555-222-3333,San Diego,"okay-quality, not bad"
3,104,Sofia O'Neill,sofia.oneill@gmail.com,555 444 5555,Chicago,I LOVE this item!!!
4,105,Daniel Lee,daniel.lee@@gmail.com,+1-555-777-8888,Houston,too expensive $$$

5 Remove extra spaces inside text

Removing the extra spaces that are inside the text uses the same function but you pass the argument of r"\s+" for the first one

In [9]:
# Remove the extra spacing in both the columns 
# of the name and the city
text_df['name'] = text_df['name'].str.replace(r"\s+", " ", regex = False)
text_df['city'] = text_df['city'].str.replace(r"\s+", " ", regex = False)
text_df.head()

,customer_id,name,email,phone,city,review
0,101,Alex Johnson,alex.johnson@gmail.com,(555) 123-4567,New York,Great product!!!
1,102,Maria Garcia,maria_garcia@yahoo.com,555.987.6543,Los Angeles,BAD service...
2,103,James Smith,james.smith@outlook.com,555-222-3333,San Diego,"okay-quality, not bad"
3,104,Sofia O'Neill,sofia.oneill@gmail.com,555 444 5555,Chicago,I LOVE this item!!!
4,105,Daniel Lee,daniel.lee@@gmail.com,+1-555-777-8888,Houston,too expensive $$$

6 Remove punctuation or symbols

Removing the punctuation or the symbols within a column with texts you need to use the .str.replace() and pass the argument r"[^a-zA-Z\s]", " ", regex = True

In [10]:
# Remove the punctuations or the symbols in the city column
text_df["city"] = text_df["city"].str.replace(r"[^a-zA-Z\s]", "", regex=True)
# Check the data frame
text_df.head()

,customer_id,name,email,phone,city,review
0,101,Alex Johnson,alex.johnson@gmail.com,(555) 123-4567,New York,Great product!!!
1,102,Maria Garcia,maria_garcia@yahoo.com,555.987.6543,Los Angeles,BAD service...
2,103,James Smith,james.smith@outlook.com,555-222-3333,San Diego,"okay-quality, not bad"
3,104,Sofia O'Neill,sofia.oneill@gmail.com,555 444 5555,Chicago,I LOVE this item!!!
4,105,Daniel Lee,daniel.lee@@gmail.com,+1-555-777-8888,Houston,too expensive $$$

7 Replace placeholder values with missing values

Replace the placeholder values such as N/A, NA, na, etc, with a an actual np.nan. Using the .str.replace()

In [11]:
# Replace all of ht placeholder values with actual np.nan
text_df = text_df.replace(["N/A", "n/a", "NA", "na", "unknown", "Unknown"], np.nan)
# Check the data frame
text_df.head()

,customer_id,name,email,phone,city,review
0,101,Alex Johnson,alex.johnson@gmail.com,(555) 123-4567,New York,Great product!!!
1,102,Maria Garcia,maria_garcia@yahoo.com,555.987.6543,Los Angeles,BAD service...
2,103,James Smith,james.smith@outlook.com,555-222-3333,San Diego,"okay-quality, not bad"
3,104,Sofia O'Neill,sofia.oneill@gmail.com,555 444 5555,Chicago,I LOVE this item!!!
4,105,Daniel Lee,daniel.lee@@gmail.com,+1-555-777-8888,Houston,too expensive $$$

8 Clean phone numbers

Cleaning the phone numbers utilizes the same function of .str.replace(), except you are passing in the argument of r"\D". Which basically removes everything and just leaves the numbers

In [13]:
# Keep only the numbers within the column for numbers
text_df['phone'] = text_df['phone'].str.replace(r"\D", "", regex = True)
# Check the dataframe
text_df.head()

,customer_id,name,email,phone,city,review
0,101,Alex Johnson,alex.johnson@gmail.com,5551234567,New York,Great product!!!
1,102,Maria Garcia,maria_garcia@yahoo.com,5559876543,Los Angeles,BAD service...
2,103,James Smith,james.smith@outlook.com,5552223333,San Diego,"okay-quality, not bad"
3,104,Sofia O'Neill,sofia.oneill@gmail.com,5554445555,Chicago,I LOVE this item!!!
4,105,Daniel Lee,daniel.lee@@gmail.com,15557778888,Houston,too expensive $$$

9 Format phone number after cleaning 

For further cleaning of the the phone numbers you can also add some formatting to the number, by using the same function of .str.replace()

In [16]:
# Refromat the phone number to match a common phone number
text_df["phone"] = text_df["phone"].str[-10:]

text_df["phone_formatted"] = (
    "(" + text_df["phone"].str[0:3] + ") " +
    text_df["phone"].str[3:6] + "-" +
    text_df["phone"].str[6:10]
)

# Check the dataframe
text_df.head()

,customer_id,name,email,phone,city,review,phone_formatted
0,101,Alex Johnson,alex.johnson@gmail.com,5551234567,New York,Great product!!!,(555) 123-4567
1,102,Maria Garcia,maria_garcia@yahoo.com,5559876543,Los Angeles,BAD service...,(555) 987-6543
2,103,James Smith,james.smith@outlook.com,5552223333,San Diego,"okay-quality, not bad",(555) 222-3333
3,104,Sofia O'Neill,sofia.oneill@gmail.com,5554445555,Chicago,I LOVE this item!!!,(555) 444-5555
4,105,Daniel Lee,daniel.lee@@gmail.com,5557778888,Houston,too expensive $$$,(555) 777-8888

10 Check whether text contains something

To be able to check whether a text contains something you can use the function of .str.contains()

In [ ]:
# Check to see if there 
# are any gmails within the email column
text_df['is_gmail'] = text_df['email'].str.contains("gmail", na=False)
# Check the dataframe
text_df.head()

11 Check if emails look valid

Checking if the emails are valid in the email column you need to be able to use the .str.contains() function and pass the regex argument of r"^[\w\.-]+@[\w\.-]+\.\w+$"

In [ ]:
# Check if the emails in the emails column 
# would be considerd as valid
text_df['valid_email'] = text_df['email'].str.contains(
    r"^[\w\.-]+@[\w\.-]+\.\w+$",
    regex = True,
    na = False
)

# Checking the dataframe
text_df.head()

12 Split text into new columns

To split the text that are in columns you need to use the function of .str.split()

In [20]:
# In the name column split the text 
# into the first name and last name
text_df[['first_name', 'last_name']] = text_df['name'].str.split(
    " ",
    n=1,
    expand = True
)

# Check data frame
text_df.head()

,customer_id,name,email,phone,city,review,phone_formatted,is_gmail,valid_email,first_name,last_name
0,101,Alex Johnson,alex.johnson@gmail.com,5551234567,New York,Great product!!!,(555) 123-4567,True,True,Alex,Johnson
1,102,Maria Garcia,maria_garcia@yahoo.com,5559876543,Los Angeles,BAD service...,(555) 987-6543,False,True,Maria,Garcia
2,103,James Smith,james.smith@outlook.com,5552223333,San Diego,"okay-quality, not bad",(555) 222-3333,False,True,James,Smith
3,104,Sofia O'Neill,sofia.oneill@gmail.com,5554445555,Chicago,I LOVE this item!!!,(555) 444-5555,True,True,Sofia,O'Neill
4,105,Daniel Lee,daniel.lee@@gmail.com,5557778888,Houston,too expensive $$$,(555) 777-8888,True,False,Daniel,Lee

13 Extract text using regex

Extracting text uses the .str.extract() function and to be able to use it you need to add the regex argument as well

In [23]:
# Extract the email domain within the email column
text_df["email_domain"] = text_df["email"].str.extract(r"@([\w\.-]+)")
# Check the data frame
text_df.head()

,customer_id,name,email,phone,city,review,phone_formatted,is_gmail,valid_email,first_name,last_name,email_domain
0,101,Alex Johnson,alex.johnson@gmail.com,5551234567,New York,Great product!!!,(555) 123-4567,True,True,Alex,Johnson,gmail.com
1,102,Maria Garcia,maria_garcia@yahoo.com,5559876543,Los Angeles,BAD service...,(555) 987-6543,False,True,Maria,Garcia,yahoo.com
2,103,James Smith,james.smith@outlook.com,5552223333,San Diego,"okay-quality, not bad",(555) 222-3333,False,True,James,Smith,outlook.com
3,104,Sofia O'Neill,sofia.oneill@gmail.com,5554445555,Chicago,I LOVE this item!!!,(555) 444-5555,True,True,Sofia,O'Neill,gmail.com
4,105,Daniel Lee,daniel.lee@@gmail.com,5557778888,Houston,too expensive $$$,(555) 777-8888,True,False,Daniel,Lee,gmail.com

14 Count text length

Counting the text length within a text column uses the function of .str.len()

In [24]:
# Find the text length of the emails
text_df['email'].str.len()

0    22
1    22
2    23
3    22
4    21
5    17
6    23
7    19
Name: email, dtype: int64

15 Chain text cleaning steps together

Finally you are able to chain all of these function and methods together to clean a whole column in a single go.

In [25]:
# Recopy the dataframe
new_df = df.copy()

In [27]:
# Completely clean the name column.
new_df["name_clean"] = (
    new_df["name"]
    .str.strip()
    .str.replace("_", " ", regex=False)
    .str.replace("-", " ", regex=False)
    .str.replace(r"\s+", " ", regex=True)
    .str.title()
)

new_df[['name_clean', 'name']]

      name_clean             name
0   Alex Johnson    alex johnson
1   Maria Garcia   MARIA   GARCIA
2    James Smith      James-smith
3  Sofia O'Neill    sofia o'neill
4     Daniel Lee     DANIEL  lee
5    Emma Watson      emma_watson
6    Chris Brown    Chris Brown
7      Mia Davis      mia   davis